apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elkdemo-kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elkdemo-kibana
    spec:
      containers:
      - name: elkdemo-kibana
        image: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_UR
          value: "http://52.233.170.164:9200/"
      imagePullSecrets:
      - name: dockerreg-secret
