apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: kibana
        env:
        - name: KIBANA_ES_URL
          value: "http://52.174.178.247:9200"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
