apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elkdemo-kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elkdemo-kibana
    spec:
      containers:
      - name: elkdemo-kibana
        image: kibana:4.6.4
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://11.11.0.100:9200/"
      imagePullSecrets:
      - name: dockerreg-secret
