apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: cvugrinec/javawebapp:1.0
        ports:
        - containerPort: 8080
